import os
from abc import ABC, abstractmethod
from dotenv import load_dotenv
import google.generativeai as genai


load_dotenv()


class BaseLLMService(ABC):

    @abstractmethod
    def generate_response(self, prompt: str) -> str:
        pass



class LLMService(BaseLLMService):

    def __init__(self):

        api_key = os.getenv("GEMINI_API_KEY")

        if not api_key:
            raise Exception(
                "GEMINI_API_KEY not found in environment variables"
            )


        genai.configure(
            api_key=api_key
        )


        self.model = genai.GenerativeModel(
            "gemini-flash-latest"
        )


    def generate_response(self, prompt: str) -> str:

        try:



            response = self.model.generate_content(
                prompt
            )




            if response.text:
                return response.text


            return "No response generated by Gemini."


        except Exception as e:

            print("Gemini Error:", repr(e))


            return (
                "Demo Mode Response:\n"
                "According to the uploaded company documents, "
                "employees are entitled to company benefits "
                "and should follow organizational policies."
            )